name: dart_mediator
description: >
  A simple yet highly configurable Mediator implementation
  that allows sending requests and publishing events.
version: 0.3.1
repository: https://github.com/MatthiWare/mediator.dart
issue_tracker: https://github.com/MatthiWare/mediator.dart/issues

topics:
  - mediator

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.9
  mocktail: ^1.0.1
