name: dart_event_manager
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/MatthiWare/event_manager.dart

environment:
  sdk: '>=2.17.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
