name: dart_event_manager
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/MatthiWare/event_manager.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mocktail: ^1.0.1
